version: '3.8'

services:
  # AI Manager Application
  ai-manager:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ai_manager:password@postgres:5432/ai_manager
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DEBUG=False
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ai-manager-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ai_manager
      - POSTGRES_USER=ai_manager
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ai-manager-network

  # Redis for background tasks
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-manager-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-manager
    restart: unless-stopped
    networks:
      - ai-manager-network

volumes:
  postgres_data:
  redis_data:

networks:
  ai-manager-network:
    driver: bridge 